### ISSUE TITLE
Should not add extra blank line when appending to file.

### ISSUE THREAD

**Issue by GrahamDumpleton** [eduk8s/eduk8s-vscode-helper#5]
When arguments resolve to appending to file and there is already a newline at the end of the file, an extra new line is being inserted before the lines added to the end of the file. Would not expect this.

In other words, if adding ``extra``, am seeing:

```
existing
lines

extra
```

instead of what expect of:

```
existing
lines
extra
```

**Comment by kdvolder** [comment]
Please provide exactly:

- the file contents including whitespace / newlines. 
- the parameters being passed to the rest endpoint

So that we can be sure we are fixing the edge-case you care about and not some other possibly similar edge case.

**Comment by kdvolder** [comment]
I'm going to make a guess here... 

Initial file contents `"existing\nlines\n"`

I'm not sure though how you specify the end of file. There's a number of ways, by line number, but a string not being found or by ommitting 'where to paste' style parameter altogether.

**Comment by kdvolder** [comment]
I guess I'll just assume we are trying to fix the 'no location parameter' case as it is probably the most logical way for caller to indicate 'paste at end' intention clearly. If you had something else in mind when reporting the bug let us know otherwise, just ignore my questions for more info.

**Comment by GrahamDumpleton** [comment]
I only pass ``file`` param for paste endpoint, nothing else, except for the content to be pasted.
